version: "3"
services:
  test:
    build: .
    ports:
      - "3005"
    container_name: rw-adapter-carto-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
    command: test
