version: "3"
services:
  test:
    build: .
    ports:
      - "3005"
    container_name: rw-adapter-carto-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3005
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: test
