apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: carto
  name: carto
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: carto
    spec:
      containers:
      - name: carto
        image: vizzuality/carto
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "3005"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://carto.default.svc.cluster.local:3005
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
        ports:
          - containerPort: 3005

      restartPolicy: Always
