apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carto
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: carto
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
